# Generated by Django 6.0.6 on 2026-06-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(blank=True, max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('url_original', models.URLField()),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_guardada', models.DateTimeField(auto_now_add=True)),
                ('vista', models.BooleanField(default=False)),
            ],
        ),
    ]
