# Generated by Django 6.0.6 on 2026-06-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='vista',
        ),
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('guardada', 'Guardada'), ('descartada', 'Descartada')], default='nueva', max_length=20),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fuente',
            field=models.CharField(default='adzuna', max_length=50),
        ),
    ]
