# Generated by Django 6.0.6 on 2026-06-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_remove_oferta_vista_oferta_estado_oferta_fuente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('vista', 'Vista'), ('guardada', 'Guardada'), ('descartada', 'Descartada')], default='nueva', max_length=20),
        ),
    ]
