# Generated by Django 6.0.6 on 2026-07-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_oferta_usuario_cvusuario_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto_mime',
            field=models.CharField(blank=True, default='image/jpeg', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
